export const DEFAULT_MOCK_LEADS = [
  {
    id: 101,
    full_name: "Alex Chen",
    job_title: "VP of Engineering",
    headline: "Building high-scale distributed systems & AI developer tools",
    company_name: "Stripe",
    industry: "Software & SaaS",
    city_name: "San Francisco",
    region_name: "California",
    country_name: "United States",
    email: "a****@stripe.com",
    linkedin_url: "https://linkedin.com/in/alexchen-eng",
    website_url: "https://stripe.com",
    about: "Engineering leader with 12+ years experience scaling payments, developer APIs, and cloud infrastructure.",
    is_verified: true,
    created_at: "2026-07-28T10:30:00Z",
  },
  {
    id: 102,
    full_name: "Elena Rostova",
    job_title: "Head of Growth & Product",
    headline: "Product-led growth, retention loops and viral distribution",
    company_name: "Linear",
    industry: "Software & SaaS",
    city_name: "London",
    region_name: "Greater London",
    country_name: "United Kingdom",
    email: "e****@linear.app",
    linkedin_url: "https://linkedin.com/in/elenarostova",
    website_url: "https://linear.app",
    about: "Passionate about building fast, intuitive software tools that software teams love using every day.",
    is_verified: true,
    created_at: "2026-07-29T14:15:00Z",
  },
  {
    id: 103,
    full_name: "Marcus Vance",
    job_title: "Chief Technology Officer",
    headline: "Open source advocate, Postgres & realtime cloud architect",
    company_name: "Supabase",
    industry: "Cloud & DevTools",
    city_name: "Austin",
    region_name: "Texas",
    country_name: "United States",
    email: "m****@supabase.com",
    linkedin_url: "https://linkedin.com/in/marcusvance",
    website_url: "https://supabase.com",
    about: "Spearheading backend systems, database clustering, and high-concurrency developer primitives.",
    is_verified: true,
    created_at: "2026-08-01T08:00:00Z",
  },
  {
    id: 104,
    full_name: "Sarah Jenkins",
    job_title: "Senior Director of Product",
    headline: "Collaborative design systems and canvas interactivity",
    company_name: "Figma",
    industry: "Design & Creative",
    city_name: "San Francisco",
    region_name: "California",
    country_name: "United States",
    email: "s****@figma.com",
    linkedin_url: "https://linkedin.com/in/sarahjenkins",
    website_url: "https://figma.com",
    about: "Leading cross-functional product design and developer handoff tooling used by millions of designers worldwide.",
    is_verified: true,
    created_at: "2026-08-02T11:45:00Z",
  },
  {
    id: 105,
    full_name: "David Thorne",
    job_title: "Founder & CEO",
    headline: "Automating enterprise workflows with multimodal LLM agents",
    company_name: "Arcane AI",
    industry: "Artificial Intelligence",
    city_name: "New York",
    region_name: "New York",
    country_name: "United States",
    email: "d****@arcane.ai",
    linkedin_url: "https://linkedin.com/in/davidthorne",
    website_url: "https://arcane.ai",
    about: "Second-time founder backed by top-tier venture funds. Research background in NLP and reinforcement learning.",
    is_verified: true,
    created_at: "2026-08-03T09:20:00Z",
  },
  {
    id: 106,
    full_name: "Priya Patel",
    job_title: "VP of Customer Success",
    headline: "Scaling global enterprise customer onboarding and retention",
    company_name: "Notion",
    industry: "Software & SaaS",
    city_name: "Toronto",
    region_name: "Ontario",
    country_name: "Canada",
    email: "p****@notion.so",
    linkedin_url: "https://linkedin.com/in/priyapatel-cs",
    website_url: "https://notion.so",
    about: "Dedicated to helping organizations transform team productivity and workplace knowledge sharing.",
    is_verified: true,
    created_at: "2026-08-04T16:10:00Z",
  },
  {
    id: 107,
    full_name: "Dr. Aris Thorne",
    job_title: "Chief Medical Officer",
    headline: "Genomics, precision medicine & clinical trial automation",
    company_name: "BioGenix Health",
    industry: "Healthcare & Biotech",
    city_name: "Boston",
    region_name: "Massachusetts",
    country_name: "United States",
    email: "a****@biogenix.health",
    linkedin_url: "https://linkedin.com/in/aristhorne-md",
    website_url: "https://biogenix.health",
    about: "Physician-scientist bridging clinical research, regulatory compliance, and cutting-edge biotech therapeutics.",
    is_verified: true,
    created_at: "2026-08-05T13:00:00Z",
  },
  {
    id: 108,
    full_name: "Sophia Lindqvist",
    job_title: "Head of Clinical Data",
    headline: "Patient registries, bio-informatics and compliance",
    company_name: "MedTech Nordic",
    industry: "Healthcare & Biotech",
    city_name: "Stockholm",
    region_name: "Stockholm County",
    country_name: "Sweden",
    email: "s****@medtechnordic.se",
    linkedin_url: "https://linkedin.com/in/sophialindqvist",
    website_url: "https://medtechnordic.se",
    about: "Expert in Nordic health data registries, European medical device regulations, and healthcare data security.",
    is_verified: true,
    created_at: "2026-08-05T15:30:00Z",
  },
  {
    id: 109,
    full_name: "Benjamin Zhao",
    job_title: "General Partner",
    headline: "Investing in Series A/B Enterprise Software & Fintech",
    company_name: "Sequoia Horizon",
    industry: "Venture Capital",
    city_name: "Menlo Park",
    region_name: "California",
    country_name: "United States",
    email: "b****@sequoiahorizon.vc",
    linkedin_url: "https://linkedin.com/in/benjaminzhao-vc",
    website_url: "https://sequoiahorizon.vc",
    about: "Investor supporting early-stage founders building transformative developer platforms and financial infrastructure.",
    is_verified: true,
    created_at: "2026-08-06T10:00:00Z",
  },
  {
    id: 110,
    full_name: "Camille Dubois",
    job_title: "Managing Director",
    headline: "European tech buyouts, growth equity & cross-border M&A",
    company_name: "Alpha Ventures",
    industry: "Finance & Private Equity",
    city_name: "Paris",
    region_name: "Île-de-France",
    country_name: "France",
    email: "c****@alphaventures.eu",
    linkedin_url: "https://linkedin.com/in/camilledubois",
    website_url: "https://alphaventures.eu",
    about: "15+ years in private capital markets, structuring high-value acquisitions and cross-border tech mergers.",
    is_verified: true,
    created_at: "2026-08-06T14:40:00Z",
  },
  {
    id: 111,
    full_name: "Lucas Moretti",
    job_title: "Head of Risk & Fraud Analytics",
    headline: "AI-driven fraud detection & algorithmic compliance",
    company_name: "Revolut",
    industry: "Fintech & Banking",
    city_name: "London",
    region_name: "Greater London",
    country_name: "United Kingdom",
    email: "l****@revolut.com",
    linkedin_url: "https://linkedin.com/in/lucasmoretti",
    website_url: "https://revolut.com",
    about: "Architecting real-time risk scoring engines, AML pipelines, and automated merchant compliance systems.",
    is_verified: true,
    created_at: "2026-08-07T09:15:00Z",
  },
  {
    id: 112,
    full_name: "Maya Alvarez",
    job_title: "Chief Marketing Officer",
    headline: "Brand positioning, content engines, and community growth",
    company_name: "Buffer",
    industry: "Marketing & Media",
    city_name: "Madrid",
    region_name: "Community of Madrid",
    country_name: "Spain",
    email: "m****@buffer.com",
    linkedin_url: "https://linkedin.com/in/mayaalvarez",
    website_url: "https://buffer.com",
    about: "Directing omnichannel organic growth, community brand advocacy, and creator monetization strategies.",
    is_verified: true,
    created_at: "2026-08-07T12:00:00Z",
  },
  {
    id: 113,
    full_name: "Daniel Kim",
    job_title: "VP of Global Partnerships",
    headline: "Strategic integrations, developer ecosystem & OEM growth",
    company_name: "Canva",
    industry: "Marketing & Media",
    city_name: "Sydney",
    region_name: "New South Wales",
    country_name: "Australia",
    email: "d****@canva.com",
    linkedin_url: "https://linkedin.com/in/danielkim-canva",
    website_url: "https://canva.com",
    about: "Connecting global platform ecosystems, creator app marketplaces, and strategic enterprise software alliances.",
    is_verified: true,
    created_at: "2026-08-08T07:45:00Z",
  },
  {
    id: 114,
    full_name: "Tariq Al-Mansoor",
    job_title: "Co-Founder & CEO",
    headline: "Next-gen sovereign cloud infrastructure and edge computing",
    company_name: "Nexus Cloud",
    industry: "Cloud & DevTools",
    city_name: "Dubai",
    region_name: "Dubai",
    country_name: "United Arab Emirates",
    email: "t****@nexuscloud.ae",
    linkedin_url: "https://linkedin.com/in/tariqalmansoor",
    website_url: "https://nexuscloud.ae",
    about: "Pioneering regional low-latency edge cloud nodes and sovereign data compliance across the MENA region.",
    is_verified: true,
    created_at: "2026-08-08T11:20:00Z",
  },
  {
    id: 115,
    full_name: "Amara Okafor",
    job_title: "Head of Payments & Operations",
    headline: "Cross-border African commerce, rails & treasury routing",
    company_name: "Flutterwave",
    industry: "Fintech & Banking",
    city_name: "Lagos",
    region_name: "Lagos State",
    country_name: "Nigeria",
    email: "a****@flutterwave.com",
    linkedin_url: "https://linkedin.com/in/amaraokafor",
    website_url: "https://flutterwave.com",
    about: "Building resilient payments infrastructure connecting African merchants with global e-commerce and banking rails.",
    is_verified: true,
    created_at: "2026-08-09T08:10:00Z",
  },
  {
    id: 116,
    full_name: "Hugo Silva",
    job_title: "VP of Product Design",
    headline: "Crafting delightful web experiences, design systems & micro-interactions",
    company_name: "Vercel",
    industry: "Design & Creative",
    city_name: "Lisbon",
    region_name: "Lisbon District",
    country_name: "Portugal",
    email: "h****@vercel.com",
    linkedin_url: "https://linkedin.com/in/hugosilva-design",
    website_url: "https://vercel.com",
    about: "Focused on frontend UX, high-polish typography, web performance, and modern developer interfaces.",
    is_verified: true,
    created_at: "2026-08-09T14:50:00Z",
  },
];
